site_name: Notas Musicais
repo_url: https://github.com/joaobrc/notas-musicais2/
repo_name: joaobrc/notas-musicais
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/note.png
  favicon: assets/note.png
  palette:
    primary: orange

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais2]